import Head from "next/head";
import Nav from "../components/Nav/Nav.js";
import Banner from "../components/Banner.js";
import About from "../components/About/About.js";
import Utility from "../components/Utility/Utility.js";
import Map from "../components/Map/Map.js";
import Faq from "../components/Faq/Faq.js";
import Footer from "../components/Footer/Footer.js";

const Home = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Nav />
      <Banner />
      <About />
      <Utility />
      <Map />
      <Faq />
      <Footer />
    </div>
  );
};

export default Home;
